#!/bin/bash
#---------------------
# Testing /usr/bin/manila-* shebangs
#---------------------
set -e

BINARIES=('manila-all' 'manila-api' 'manila-manage' 'manila-rootwrap' \
          'manila-scheduler' 'manila-share' 'manila-wsgi')

ret=0

for binary in "${BINARIES[@]}"; do
    if ! `dirname $0`/test-shebang.py $binary python3; then
        ret=1
    fi
done

exit $ret
