#!/bin/bash
#---------------------
# Testing manila-daemons
#---------------------
set -e
DAEMONS=('manila-api' 'manila-data' 'manila-scheduler')

for daemon in "${DAEMONS[@]}"; do
    systemctl stop $daemon
done

ret=0

mysql -u root << EOF
DROP DATABASE IF EXISTS manila;
CREATE DATABASE manila;
GRANT ALL PRIVILEGES ON manila.* TO 'manila'@'localhost' \
  IDENTIFIED BY 'changeme';
GRANT ALL PRIVILEGES ON manila.* TO 'manila'@'%' \
  IDENTIFIED BY 'changeme';
EOF

crudini --set /etc/manila/manila.conf database connection "mysql://manila:changeme@localhost/manila"

manila-manage db sync

for daemon in "${DAEMONS[@]}"; do
    systemctl start $daemon
done

for daemon in "${DAEMONS[@]}"; do
    TIMEOUT=50
    while [ "$TIMEOUT" -gt 0 ]; do
        if systemctl is-active $daemon > /dev/null; then
            echo "OK"
            break
        fi
        TIMEOUT=$((TIMEOUT - 1))
        sleep 0.1
    done

    if [ "$TIMEOUT" -le 0 ]; then
        echo "ERROR: ${daemon} IS NOT RUNNING"
        ret=1
    fi
done

exit $ret

