#!/bin/bash
#-------------------------
# Testing client utilities
#-------------------------
set -e

result=$(python `dirname $0`/tests_import_manila.py 2>&1)
if [ "$result" ]; then
    echo "ERROR: PYTHON-MANILA MODULE CANNOT BE IMPORTED"
    exit 1
else
    echo "OK"
    exit 0
fi
